version: '1.0'
services:

  coinbase_neuranft_backend:
    build:
      context: ./master_node  # Build the image from the Dockerfile in ./master_node
    ports:
      - "0.0.0.0:6010:5500"  # Map host port 6010 to container port 5500
    volumes:
      - ./master_node:/app  # Mount the ./master_node folder into the container
      - ./master_node/.logs:/app/.logs  # Mount the .logs folder to persist logs
    # environment:
      # - FLASK_ENV=development  # Optional: Set Flask to development mode
    container_name: coinbase_neuranft_backend_container

    command: >
      gunicorn -w 1 -b 0.0.0.0:5500 app:app 
      --access-logfile /app/.logs/access.log 
      --error-logfile /app/.logs/error.log

  coinbase_neuranft_frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "6011:80"
    volumes:
      - ./frontend/.logs:/var/log/nginx
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    command: ["nginx", "-g", "daemon off;"]

    networks:
      - base_neuranft_network

  # goaccess_frontend:
  #   image: allinurl/goaccess:latest
  #   ports:
  #     - "7890:7890"  # Real-time updates port
  #   volumes:
  #     - ./frontend/.logs:/var/log/nginx:ro
  #     - ./frontend/nginx_config/goaccess.conf:/etc/goaccess/goaccess.conf:ro
  #   command: >
  #     goaccess 
  #     --config-file=/etc/goaccess/goaccess.conf
  #     --log-file=/var/log/nginx/access.log
  #     --real-time-html
  #     --port=7890
  #     --ws-url=ws://0.0.0.0:7890
  #     --output=/var/log/nginx/report.html
  #     --real-os
  #     --keep-last=30
  #     --no-global-config
  #     --origin=*
  #     --daemonize
  #   environment:
  #     - GOACCESS_WEBSOCKET_URL=ws://localhost:7890
  #   networks:
  #     - base_neuranft_network
  #   depends_on:
  #     - coinbase_neuranft_frontend

networks:
  base_neuranft_network:
    driver: bridge

